version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server

networks:
  prueba:
    name: prueba
