version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      ejercicios_servicios:
        ipv4_address: 10.10.10.10

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      ejercicios_servicios:
        ipv4_address: 10.10.10.20

networks:
  ejercicios_servicios:
    name: ejercicios_servicios
    ipam:  
      config:
        - subnet: "10.10.10.0/24"
