version: '3'
services:
  server:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    command: /bin/sh -c "while sleep 1000; do :; done"

  client:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
